#!/usr/bin/env python3

import sys
import time
import base64
import random

import grpc

# Generated by the protobuf compiler from the .proto file.
# grpc_service_pb2 contains message classes (like addMsg, rawImageMsg, …).
# grpc_service_pb2_grpc contains the generated client 
# stub class (gRPCServiceStub) and server service base.

import grpc_service_pb2
import grpc_service_pb2_grpc

# RPC = Remote Procedure Call
# gRPC is general purpose, language agnostic, open source
# gRPC uses HTTP/2 - binary framing, multiplexing, header compression
# gRPC uses Protobuf as its interface definition language (IDL)
#      - allows for the contract between the server and the client
#      - supports forwards and backwards compatibility
#      - generates the code needed for the contract
#      - runtime libraries for data serialization.

IMAGE_FILE = "Flatirons_Winter_Sunrise_edit_2.jpg"
GRPC_PORT = 50051

# Defines a helper function that sets up the gRPC client pieces.
# grpc.insecure_channel(...): Creates a client connection to host:50051.
# “insecure” means no TLS encryption <- this is okay for the purpose of 
# this lab
# gRPCServiceStub(channel): Creates an object with Python methods 
# corresponding to RPCs defined in the .proto.
# Example: stub.Add(...), stub.RawImage(...), etc.
# Returns both: channel (so we can close it later) and
# stub so we can make calls.
# gRPC channel: - Opens a TCP connection to the server
# - Uses HTTP/2 under the hood
# - Handles connection reuse, multiplexing (sending multiple requests at 
# the same time over a single network connection. 
# - retries and load balancing if configured
# - Stays open across multiple RPC calls - persistent highway bt client and server
#   (Unlike basic REST clients that often create a new HTTP connection per request,
#   gRPC keeps one open and reuses it.)
# stub: client-side object that lets you call remote functions like they’re 
#       local functions. 
# - Serializes the request into protobuf binary
# - Sends it over the channel
# - Waits for server response
# - Deserializes the response and returns it

def make_stub(host: str):
    channel = grpc.insecure_channel(f"{host}:{GRPC_PORT}")
    stub = grpc_service_pb2_grpc.gRPCServiceStub(channel)
    return channel, stub


def doAdd(stub, debug=False):
    req = grpc_service_pb2.addMsg(a=5, b=10)
    resp = stub.Add(req)
    if debug:
        print("Add reply:", resp)


def doRawImage(stub, img_bytes: bytes, debug=False):
    req = grpc_service_pb2.rawImageMsg(img=img_bytes)
    resp = stub.RawImage(req)
    if debug:
        print("RawImage reply:", resp)


def doJsonImage(stub, img_b64: str, debug=False):
    # jsonImageMsg has a string field (base64 image) for consistency with REST
    req = grpc_service_pb2.jsonImageMsg(img=img_b64)
    resp = stub.JsonImage(req)
    if debug:
        print("JsonImage reply:", resp)


def doDotProduct(stub, vec_a, vec_b, debug=False):
    req = grpc_service_pb2.dotProductMsg(a=vec_a, b=vec_b)
    resp = stub.DotProduct(req)
    if debug:
        print("DotProduct reply:", resp)


def usage():
    print(f"Usage: {sys.argv[0]} <server host> <cmd> <reps> [debug]")
    print("  <cmd> one of: add, rawImage, jsonImage, dotProduct")
    print("  <reps> integer number of repetitions for measurement")
    print("  [debug] optional: if provided, prints a sample response")


# The following block of code:
# - Chooses which RPC to test
# - Executes it N times
# - Reports average latency per request

def main():
    if len(sys.argv) < 4:
        usage()
        sys.exit(1)

    # pull off the arguments that are passed when calling the program
    # For example, python grpc-client.py localhost add 1000 results in:
    # sys.argv[0] = "grpc-client.py"
    # host = sys.argv[1] = "localhost"
    # cmd = sys.argv[2] = "add" <- our endpoint of interest
    # reps = sys.argv[3] = "1000" <- number of HTTP requests
    host = sys.argv[1]
    cmd = sys.argv[2]
    reps = int(sys.argv[3])
    debug = (len(sys.argv) >= 5)

    # Prepare payloads once so timing measures RPC more than setup/file IO
    img_bytes = None
    img_b64 = None
    vec_a = None
    vec_b = None

    if cmd in ("rawImage", "jsonImage"):
        with open(IMAGE_FILE, "rb") as f:
            img_bytes = f.read()
        img_b64 = base64.b64encode(img_bytes).decode("utf-8")

    if cmd == "dotProduct":
        size = 100
        vec_a = [random.random() for _ in range(size)]
        vec_b = [random.random() for _ in range(size)]

    channel, stub = make_stub(host)
    print(f"Running {reps} reps against {host}:{GRPC_PORT} (cmd={cmd})")

    try:
        start = time.perf_counter()

        if cmd == "add":
            for _ in range(reps):
                doAdd(stub, debug=False)

        elif cmd == "rawImage":
            for _ in range(reps):
                doRawImage(stub, img_bytes, debug=False)

        elif cmd == "jsonImage":
            for _ in range(reps):
                doJsonImage(stub, img_b64, debug=False)

        elif cmd == "dotProduct":
            for _ in range(reps):
                doDotProduct(stub, vec_a, vec_b, debug=False)

        else:
            print("Unknown option:", cmd)
            usage()
            sys.exit(1)
        # As noted above about the channel,
        # gRPC is different from REST in that all iterations reuse one 
        # persistent connection
        delta_ms = ((time.perf_counter() - start) / reps) * 1000.0
        print("Took", delta_ms, "ms per operation")

        # Optional debug: do one extra call and print response
        if debug:
            print("\n--- Debug: sample response ---")
            if cmd == "add":
                doAdd(stub, debug=True)
            elif cmd == "rawImage":
                doRawImage(stub, img_bytes, debug=True)
            elif cmd == "jsonImage":
                doJsonImage(stub, img_b64, debug=True)
            elif cmd == "dotProduct":
                doDotProduct(stub, vec_a, vec_b, debug=True)

    # Closes the gRPC channel
    finally:
        channel.close()


if __name__ == "__main__":
    main()

# NOTES: Run the code with these commands for each output
# python3 grpc-client.py localhost add 1000
# python3 grpc-client.py localhost rawImage 100
# python3 grpc-client.py localhost jsonImage 100
# python3 grpc-client.py localhost dotProduct 1000